// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbB-CmwKnHeDgQmfkhSUmn3nN_pMdxHlc',
    appId: '1:736390742287:web:54981f0855015be60d3e7a',
    messagingSenderId: '736390742287',
    projectId: 'eventlyapp-8a51d',
    authDomain: 'eventlyapp-8a51d.firebaseapp.com',
    storageBucket: 'eventlyapp-8a51d.firebasestorage.app',
    measurementId: 'G-WLNJRHS2V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASjYNTh40yw2Zr1IOaSbi9zw_r6MSDL2U',
    appId: '1:736390742287:android:f85ede5c9deb37910d3e7a',
    messagingSenderId: '736390742287',
    projectId: 'eventlyapp-8a51d',
    storageBucket: 'eventlyapp-8a51d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl-UeFz64lmSktegM-wg0phbUOjnfxEj0',
    appId: '1:736390742287:ios:53d84ac61ce007350d3e7a',
    messagingSenderId: '736390742287',
    projectId: 'eventlyapp-8a51d',
    storageBucket: 'eventlyapp-8a51d.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl-UeFz64lmSktegM-wg0phbUOjnfxEj0',
    appId: '1:736390742287:ios:53d84ac61ce007350d3e7a',
    messagingSenderId: '736390742287',
    projectId: 'eventlyapp-8a51d',
    storageBucket: 'eventlyapp-8a51d.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbB-CmwKnHeDgQmfkhSUmn3nN_pMdxHlc',
    appId: '1:736390742287:web:20fd8e1cfe31d9520d3e7a',
    messagingSenderId: '736390742287',
    projectId: 'eventlyapp-8a51d',
    authDomain: 'eventlyapp-8a51d.firebaseapp.com',
    storageBucket: 'eventlyapp-8a51d.firebasestorage.app',
    measurementId: 'G-VL1C4WPCGE',
  );

}